FROM golang:1.24-alpine AS builder
WORKDIR /app
COPY . .
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o /order-service ./services/order-service/cmd

FROM alpine:latest
COPY --from=builder /order-service /order-service
EXPOSE 8080
ENTRYPOINT ["/order-service"]